### ISSUE TITLE
Generiic emitter for any topic

### ISSUE THREAD

**Issue by mostafacs** [cescoffier/getting-started-quarkus-kafka#2]
currently, I can create an emitter and configure it in `applications.properties` . Then i can inject it and use like that.
```
    @Inject @Channel("movies-out")
    Emitter<Record<Integer, String>> emitter;
```

I hope if there's a feature similar to the default KafkaProducer so I can programmatically set the TopicName, Record ...
```
        ProducerRecord<Integer, RawListingRequest> newRecord = new
                ProducerRecord(topicName, record.key(), record.value());
        producer.send(newRecord);

```

Is that already possible?

**Comment by cescoffier** [comment]
Yes, using Metadata. 
Check the Outbound Metadata section from https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/kafka/kafka.html#kafka-outbound
